production:
  clients:
    default:
      database: seo_monitor_production
      hosts:
        - <%= ENV['MONGO_HOST'] %>:27017
      options:
        server_selection_timeout: 5
        connect_timeout: 5

development:
  clients:
    default:
      database: seo_monitor_development
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost' %>:27017
      options:
        server_selection_timeout: 1