development:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URL', 'mongodb://localhost:27017/seo_monitor_development') %>
  options: {}

production:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URL', 'mongodb://localhost:27017/seo_monitor_production') %>
  options: {}