development:
  clients:
    default:
      database: seo_monitor_development
      hosts:
        - localhost:27017
      options: {}
  options: {}

production:
  clients:
    default:
      database: seo_monitor_production
      hosts:
        - localhost:27017
      options: {}
  options: {}